CREATE TYPE travel_category AS ENUM (
  'Accommodations',
  'Rentals',
  'Activity',
  'Event',
  'Dining and Bars'
);

CREATE TABLE activity_items (
  -- id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  id SERIAL PRIMARY KEY,
  travel_type travel_category,
  title TEXT NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  start_time TIME, 
  end_time TIME,
  cost NUMERIC,
  url TEXT,
  itinerary_id INTEGER REFERENCES itineraries(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);